---
# Source: app/templates/services/fake-smtp.yaml
apiVersion: v1
kind: Service
metadata:
  name: fake-smtp
spec:
  selector:
    app: fake-smtp
  ports:
    - protocol: TCP
      port: 1025
      targetPort: 1025
      name: smtp
    - protocol: TCP
      port: 1080
      targetPort: 1080
      name: web
  type: ClusterIP
