apiVersion: v1
kind: Service
metadata:
  name: fake-smtp
spec:
  selector:
    app: fake-smtp
  ports:
    - name: smtp
      protocol: TCP
      port: 25
      targetPort: 25
    - name: http
      protocol: TCP
      port: 1080
      targetPort: 1080
      nodePort: 30001
  type: NodePort
