---
# Source: app/templates/deployments/fake-smtp.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-smtp
  labels:
    app: fake-smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-smtp
  template:
    metadata:
      labels:
        app: fake-smtp
    spec:
      containers:
      - name: fake-smtp
        image: "reachfive/fake-smtp-server:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1025  # SMTP port
        - containerPort: 1080  # HTTP web interface
