---
# Source: app/templates/secrets/db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DATABASE_URL: "amRiYzpwb3N0Z3Jlc3FsOi8veW91ci1uZW9uLWRiLWhvc3QveW91ci1kYXRhYmFzZS1uYW1l"
  DATABASE_USERNAME: "eW91ci11c2VybmFtZQ=="
  DATABASE_PASSWORD: "eW91ci1wYXNzd29yZA=="
