apiVersion: v1
kind: ConfigMap
metadata:
  name: file-service-config
  labels:
    app: file-service
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  LOGGING_LEVEL_ROOT: "INFO"
  SERVER_PORT: "9091"
  DATA_SERVICE_BASE-URL: "http://data-service:9090"
