{{- if .Values.dataService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dataService.name }}
spec:
  selector:
    {{- include "app.serviceSelectorLabels" .Values.dataService.name | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.dataService.port }}
      targetPort: {{ .Values.dataService.port }}
  type: {{ .Values.serviceType }}
{{- end }}
